# Usa a mesma imagem base do Python.
FROM python:3.11-slim

# Define o diretório de trabalho.
WORKDIR /app

# Copia e instala as mesmas dependências.
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copia o código do ETL e os dados CSV para dentro do contentor.
COPY ./etl /app/etl
COPY ./data /app/data
COPY ./sql /app/sql

# O comando para executar o script ETL quando o contentor iniciar.
CMD ["python", "etl/main_etl.py"]
